back/src/Entity/Club.php
<?php

namespace App\Entity;

use App\Repository\ClubRepository;
use ApiPlatform\Metadata\ApiResource;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


#[ORM\Entity(repositoryClass: ClubRepository::class)]
#[ApiResource]
#[Vich\Uploadable]
class Club
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;
  

    #[ORM\Column]
    private ?int $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[Gedmo\Timestampable(on:"create")]
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $created_at = null;

    #[Gedmo\Timestampable(on:"update")]
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at;
/**
 * Note : This is not a mapped field of entity 
 */
   #[Vich\UploadableField(mapping :"club_logo", fileNameProperty :"imageName")]
    private ?File $imageFile = null ;
    #[ORM\Column(type :'string', nullable: true)]
    private ?string $imageName =null; 
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
/**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updated_at = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }




    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }
    }

back/src/Form/ClubType.php
<?php

namespace App\Form;

use App\Entity\Club;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClubType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('telephone')
            ->add('description')
            ->add('logo')
            ->add('imageFile', VichImageType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Club::class,
        ]);
    }
}

back/src/Controller/ClubController.php
<?php

namespace App\Controller;

use App\Entity\Club;
use App\Form\ClubType;
use App\Repository\ClubRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

//use Symfony\Component\HttpFoundation\JsonResponse;

#[Route('/club')]
class ClubController extends AbstractController
{
    #[Route('/', name: 'app_club_index', methods: ['GET'])]
    public function index(ManagerRegistry $doctrine): JsonResponse
    {
       
        $club = $doctrine->getRepository(Club::class)->findAll();
        return $this->json(
            $club
        );
    }

    #[Route('/new', name: 'app_club_new', methods: ['POST'])]
    public function new(Request $request, ManagerRegistry $doctrine): Response
    {
        $club = new Club();
        $parameter = json_decode($request->getContent(), true);
        $club->setName($parameter['name']);
        $club->setTelephone($parameter['phone']);
        $club->setDescription($parameter['description']);
        $club->setLogo($parameter['logo']);
      /*   $club->setImageName(($parameter['imageName'])); */
        /*         $club->setImageName($parameter['imageName']);
 */
        /*  $errors = $validator->validate($club);
            if ($errors->count() > 0) {
    return new JsonResponse($serializer->serialize($errors, 'json'), JsonResponse::HTTP_BAD_REQUEST, [], true);
} */
        //  $club_create = $doctrine->getRepository(Club::class)->add($club);

        $em = $doctrine->getManager();
        $em->persist($club);
        $em->flush($club);

        return $this->json([
            'club' => "Updated"
        ]);
    }

    #[Route('/{id}', name: 'app_club_show')]
    public function show(Club $club, ManagerRegistry $doctrine, int $id): Response
    {
        $text='description';
        $club = $doctrine->getRepository(Club::class)->find($id);
        if (!$club) {
            throw $this->createNotFoundException(
                'no Club found for id ' . $id
            );
        }
        return $this->json($club,$text);
    }

    #[Route('/{id}/{name}', name: 'app_club_showClub', methods: ['GET'])]
public function showClub(Club $club, ManagerRegistry $doctrine, int $id, string $name): Response
{
    $club = $doctrine->getRepository(Club::class)->find($id);
    if (!$club) {
        throw $this->createNotFoundException(
            'no Club found for id ' . $id
        );
    }
    if ($club->getName() !== $name) {
        throw $this->createNotFoundException(
            'id and name do not correspond to the same club'
        );
    }
    return $this->json($club);
}
    #[Route('/edit/{id}', name: 'app_club_edit', methods: ['PUT'])]
    public function edit(Request $request, Club $club, ClubRepository $clubRepository, ManagerRegistry $doctrine, $id): Response
    {
        $entityManager = $doctrine->getManager();
        $club = $entityManager->getRepository(Club::class)->find($id);
        if (!$club) {
            throw $this->createNotFoundException(
                'No club found for id ' . $id
            );
        }
        $parameter = json_decode($request->getContent(), true);
        $club->setName($parameter['name']);
        $club->setTelephone($parameter['telephone']);
        $club->setDescription($parameter['description']);
        $club->setLogo($parameter['logo']);
       /*  $club->setImageName($parameter['imageName']); */

        $entityManager->flush();
        return $this->json([
            'club' => "Updated"
        ]);
    }

    #[Route('/{id}', name: 'app_club_delete', methods: ['DELETE'])]
    public function delete(ManagerRegistry $doctrine, $id): Response
    {

        $entityManager = $doctrine->getManager();
        $club = $entityManager->getRepository(Club::class)->find($id);

        if (!$club) {

            throw $this->createNotFoundException(
                'No club found for  id ' . $id
            );
        }
        /*  $entityManager->getRepository(Club::class)->remove($club); 
            return $this->json([
                'club' => $club
            ]); */
        $em = $doctrine->getManager();
        $em->remove($club);
        $em->flush($club);

        return new JsonResponse(null, Response::HTTP_NO_CONTENT, ['Club' => "Deleted"]);
    }
}

back/templates/club/_delete_form.html.twig
<form method="post" action="{{ path('app_club_delete', {'id': club.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ club.id) }}">
    <button class="btn">Delete</button>
</form>

back/templates/club/_form.html.twig
{{ form_start(form) }}
    <div class="form-group">
        {{ form_row(form.name, {'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.description, {'attr': {'class': 'form-control'}}) }}
    </div>
     <div class="form-group">
        {{ form_row(form.telephone, {'attr': {'class': 'form-control'}}) }}
    </div>
     <div class="form-group">
        {{ form_row(form.logo, {'attr': {'class': 'form-control'}}) }}
    </div>
    <button class="btn {{ button_color|default('btn-outline-primary') }}  mt-3">{{ button_label|default('Save Club') }}</button>
{{ form_end(form) }}

back/templates/club/edit.html.twig
  
{% extends 'base.html.twig' %}
{% block title %}Edit Club{% endblock %}
  
{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Edit Club</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_club_index') }}"> 
                    View All Club
                </a>
            </div>
            <div class="card-body">
                {% include 'Club/_form.html.twig' with {'button_label': 'Update Club', 'button_color': 'btn-outline-success'}  %} 
                  <a href="{{ path('app_club_index') }}">back to list</a>

                  {{ include('club/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
  
{% endblock %}

back/templates/club/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Club List{% endblock %}

{% block body %}
    


  

  

    <div class="container">
        <h2 class="text-center mt-5 mb-3">Club Manager</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-primary" href="{{ path('app_club_new') }}"> 
                    Create New Club 
                </a>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <tr>
                        <th>Name</th>
                        <th>Telephone</th>
                        <th>Description</th>
                        <th>Logo</th>
                        <th>Date Created</th>
                        <th>Date Updated</th>
                        <th width="240px">Action</th>
                    </tr>
                    {% for club in clubs %}
                    <tr>
                        <td>{{ club.name }}</td>
                         <td>{{ club.telephone }}</td>
                        <td>{{ club.description }}</td>
                           <td>{{ club.logo}}</td>
                        <td>{{ club.createdAt ? club.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ club.updatedAt ? club.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>
                            <form method="post" action="{{ path('app_club_delete', {'id': club.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                <a
                                    class="btn btn-outline-info"
                                    href="{{ path('app_club_show', {'id': club.id}) }}">
                                    Show
                                </a>
                                <a
                                    class="btn btn-outline-success"
                                    href="{{ path('app_club_edit', {'id': club.id}) }}">
                                    Edit
                                </a>
  
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ club.id) }}">
                                <button class="btn btn-outline-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
  
{% endblock %}

back/templates/club/new.html.twig
{% extends 'base.html.twig' %}
  
{% block title %}New Club{% endblock %}
  
{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Create Club</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_club_index') }}"> 
                    View All Clubs
                </a>
            </div>
            <div class="card-body">
                 {{ include('club/_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

back/templates/club/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Club{% endblock %}

{% block body %}
    <h1>Club</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ club.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ club.name }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ club.telephone }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ club.description }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ club.createdAt ? club.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ club.updatedAt ? club.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Logo</th>
                <td>{{ club.logo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_club_index') }}">back to list</a>

    <a href="{{ path('app_club_edit', {'id': club.id}) }}">edit</a>

    {{ include('club/_delete_form.html.twig') }}
{% endblock %}